import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Dashboard from "../components/Dashboard/Dashboard";
import Introduction from "../components/Introduction";

const Home: NextPage = () => {
  const session = useSession();
  const userId = session.data?.user?.id;
  const btnClick = () => (userId ? signOut() : signIn());
  const btnMsg = userId ? "Sign Out" : "Sign In";
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between border-b-2 border-violet-500 bg-violet-900 p-4">
        <div className="text-4xl font-bold text-white">Turl</div>
        {session.status !== "loading" && (
          <button
            onClick={btnClick}
            className="ml-4 rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
          >
            {btnMsg}
          </button>
        )}
      </header>
      <main className="flex justify-center py-4 px-4 lg:px-10">
        {userId ? <Dashboard /> : <Introduction />}
      </main>
    </>
  );
};

export default Home;
